export const MAX_MESSAGES = 10000;
export const LOST_TIMEOUT = 2000;

export const groupSymbols: Record<string, string> = {
  VN30: "ACB,BCM,BID,CTG,DGC,FPT,GAS,GVR,HDB,HPG,LPB,MBB,MSN,MWG,PLX,SAB,SHB,SSB,SSI,STB,TCB,TPB,VCB,VHM,VIB,VIC,VJC,VNM,VPB,VRE",
  HNX30:
    "BVS,CAP,CEO,DHT,DTD,DVM,DXP,HUT,IDC,IDV,L14,L18,LAS,LHC,MBS,NTP,PLC,PSD,PVB,PVC,PVI,PVS,SHS,SLS,TMB,TNG,TVD,VC3,VCS,VGP",
};
